import { VALUE, id, pool, registryCall } from './shared.js';

const INACTIVITY = 30 * 60 * 1000;
const ROUND = 30 * 1000;

export class GrabbleRoom {
  constructor(state, env) {
    this.state = state; this.env = env; this.clients = new Map(); this.roles = new Map(); this.loaded = false;
    this.data = { code: '', phase: 'lobby', mode: 'single', round: 1, totalRounds: 1, ownerId: null, players: [], pool: pool(), gestures: {}, endAt: 0, finalCloseAt: 0, lastActivity: Date.now(), seq: 0, message: 'Waiting for players' };
  }
  async ensureLoaded() { if (this.loaded) return; const saved = await this.state.storage.get('room:data'); if (saved) this.data = { ...this.data, ...saved }; this.loaded = true; }
  async save() { await this.state.storage.put('room:data', this.data); }
  async fetch(req) {
    await this.ensureLoaded(); const u = new URL(req.url);
    if (u.pathname === '/init') return this.init(req);
    if (u.pathname === '/admin/kill') { await this.closeRoom(); return new Response('killed'); }
    if (u.pathname.startsWith('/dictionary/') && req.method === 'GET') return this.dictionaryHttp(decodeURIComponent(u.pathname.slice(11)).toLowerCase());
    await this.expireIfNeeded();
    if (req.headers.get('Upgrade') !== 'websocket') return Response.json(this.safe());
    const role = u.searchParams.get('role') || 'display', name = (u.searchParams.get('name') || 'Display').slice(0, 18), playerToken = (u.searchParams.get('playerToken') || '').slice(0, 160), controlToken = (u.searchParams.get('controlToken') || '').slice(0, 160), existing = role === 'play' && playerToken ? this.data.players.find(p => p.playerToken === playerToken) : null;
    const displayToken = (u.searchParams.get('displayToken') || '').slice(0, 160);
    if ((role === 'tv' || role === 'host') && (!controlToken || controlToken !== this.data.controlToken)) return Response.json({ error: 'UNAUTHORISED_CONTROL_ROLE' }, { status: 401 });
    if (role === 'display' && (!displayToken || displayToken !== this.data.displayToken)) return Response.json({ error: 'UNAUTHORISED_DISPLAY_ROLE' }, { status: 401 });
    if (role === 'play' && !existing && this.data.phase !== 'lobby') return Response.json({ error: 'ROUND_ALREADY_STARTED' }, { status: 409 });
    const pair = new WebSocketPair(), client = pair[0], socket = pair[1], clientId = crypto.randomUUID(); socket.accept(); this.clients.set(clientId, socket); this.roles.set(clientId, role);
    let token = playerToken;
    if (role === 'play') {
      if (existing) { existing.id = clientId; existing.name = name || existing.name; token = existing.playerToken; }
      else { token = crypto.randomUUID() + crypto.randomUUID(); if (!this.data.ownerId) this.data.ownerId = clientId; this.data.players.push({ id: clientId, playerToken: token, name, word: '', wordTiles: [], score: 0, totalScore: 0 }); this.event('player_joined', { playerId: clientId, name }); }
    }
    await this.activity(); this.send(socket, 'hello', { playerId: clientId, playerToken: role === 'play' ? token : undefined }); this.send(socket, 'authenticated', { role, playerId: clientId }); this.send(socket, 'snapshot', this.safe()); this.broadcastSnapshot();
    socket.addEventListener('message', e => this.action(clientId, role, e.data));
    socket.addEventListener('close', () => { for (const t of this.data.pool) if (t.reservedBy === clientId) { delete t.reservedBy; delete t.reservedAt; } this.clients.delete(clientId); this.roles.delete(clientId); delete this.data.gestures[clientId]; this.broadcastSnapshot(); this.activity(); });
    return new Response(null, { status: 101, webSocket: client });
  }
  async init(req) { let x = {}; try { x = await req.json(); } catch {} this.data = { ...this.data, code: x.code || this.data.code, phase: 'lobby', mode: x.mode === 'competition' ? 'competition' : 'single', round: 1, totalRounds: x.mode === 'competition' ? 5 : 1, ownerId: null, players: [], pool: pool(), gestures: {}, endAt: 0, finalCloseAt: 0, lastActivity: Date.now(), seq: 0, message: 'Waiting for players', controlToken: x.controlToken || this.data.controlToken || '', displayToken: x.displayToken || this.data.displayToken || '' }; await this.save(); return new Response('ok'); }
  safe() { const reveal = ['scoring', 'results', 'final'].includes(this.data.phase); return { phase: this.data.phase, mode: this.data.mode, round: this.data.round, totalRounds: this.data.totalRounds, ownerId: this.data.ownerId, players: this.data.players.map(p => ({ id: p.id, name: p.name, word: p.word, wordTiles: reveal ? (p.wordTiles || []) : undefined, score: p.score, totalScore: p.totalScore, validation: p.validation })), gestures: Object.values(this.data.gestures || {}).filter(g => Date.now() - g.at < 1800), pool: this.data.pool.map(t => ({ id: t.id, letter: t.letter, bonus: reveal ? (t.bonus || null) : null, reservedBy: t.reservedBy || null })), endAt: this.data.endAt, message: this.data.message }; }
  send(socket, type, payload) { try { socket.send(JSON.stringify({ v: 1, type, seq: this.data.seq, phase: this.data.phase, payload })); } catch {} }
  broadcastSnapshot() { this.data.seq++; const snapshot = this.safe(); for (const socket of this.clients.values()) this.send(socket, 'snapshot', snapshot); this.event('state_changed', { state: snapshot }); this.save(); }
  event(type, payload = {}) { this.data.seq++; for (const socket of this.clients.values()) this.send(socket, type, payload); this.save(); }
  reply(socket, type, payload = {}, requestId) { this.send(socket, type, { requestId, ...payload }); }
  error(socket, code, message, requestId) { this.reply(socket, 'error', { code, message }, requestId); }
  async activity() { this.data.lastActivity = Date.now(); await this.save(); this.state.storage.setAlarm(this.nextAlarm()).catch(() => {}); }
  nextAlarm() { const deadlines = [this.data.lastActivity + INACTIVITY]; if (this.data.endAt) deadlines.push(Math.min(this.data.endAt, Date.now() + 1000)); if (this.data.finalCloseAt) deadlines.push(this.data.finalCloseAt); return Math.min(...deadlines); }
  async expireIfNeeded() { const now = Date.now(); if (this.data.phase === 'closed') return; if (now - this.data.lastActivity >= INACTIVITY) return this.closeRoom(); if (['countdown', 'running'].includes(this.data.phase) && this.data.endAt && now < this.data.endAt) { this.event('timer_updated', { phase: this.data.phase, endAt: this.data.endAt }); return; } if (this.data.phase === 'countdown' && now >= this.data.endAt) return this.beginRound(); if (this.data.phase === 'running' && now >= this.data.endAt) { this.data.phase = 'scoring'; this.event('phase_changed', { phase: 'scoring' }); this.data.endAt = 0; this.data.message = 'Scoring…'; this.broadcastSnapshot(); await this.finish(); this.event('score_updated', { players: this.data.players.map(p => ({ id: p.id, score: p.score, totalScore: p.totalScore, validation: p.validation })) }); this.data.phase = this.data.round === this.data.totalRounds ? 'final' : 'results'; this.data.message = this.data.phase === 'final' ? 'Competition complete' : 'Round complete'; if (this.data.phase === 'final') this.data.finalCloseAt = now + 300000; this.event('phase_changed', { phase: this.data.phase }); this.event('finished', { phase: this.data.phase, round: this.data.round }); this.broadcastSnapshot(); } else if (['results', 'final'].includes(this.data.phase) && this.data.finalCloseAt && now >= this.data.finalCloseAt) return this.closeRoom(); }
  async alarm() { await this.ensureLoaded(); await this.expireIfNeeded(); if (this.data.phase !== 'closed') await this.activity(); }
  async closeRoom() { if (this.data.phase === 'closed') return; this.data.phase = 'closed'; this.data.endAt = 0; this.data.finalCloseAt = 0; this.data.message = 'Room closed'; this.event('phase_changed', { phase: 'closed' }); this.event('room_closed', { roomId: this.data.code }); this.broadcastSnapshot(); await this.state.storage.deleteAlarm().catch(() => {}); for (const socket of this.clients.values()) try { socket.close(1000, 'Room closed'); } catch {} this.clients.clear(); await registryCall(this.env, '/unregister/' + encodeURIComponent(this.data.code), { gameId: 'grabble', roomId: this.data.code, roomCode: this.data.code }).catch(() => {}); }
  async dictionaryHttp(word) { if (!/^[a-z]{3,}$/.test(word)) return Response.json({ valid: false }); const key = 'dictionary:' + word, cached = await this.state.storage.get(key); if (cached && cached.expiresAt > Date.now()) return Response.json({ valid: cached.valid }); try { const r = await fetch('https://api.dictionaryapi.dev/api/v2/entries/en/' + encodeURIComponent(word)); if (r.ok || r.status === 404) { const valid = r.ok; await this.state.storage.put(key, { valid, expiresAt: Date.now() + (valid ? 30 : 1) * 86400000 }); return Response.json({ valid }); } } catch {} return Response.json({ valid: null }); }
  async dictionaryWord(word) { try { const admin = this.env.ADMIN.get(this.env.ADMIN.idFromName('global')), cfg = await (await admin.fetch('https://admin/config')).json(), r = await admin.fetch('https://admin/' + (cfg.dictionaryProvider === 'dictionaryapi' ? 'dictionary' : 'datamuse') + '/' + encodeURIComponent(word)); return (await r.json()).valid; } catch { return null; } }
  async dictionaryPattern(word) { const chars = [...String(word || '').toLowerCase()]; const walk = async i => { while (i < chars.length && chars[i] !== '*') i++; if (i === chars.length) return this.dictionaryWord(chars.join('')); for (const letter of 'abcdefghijklmnopqrstuvwxyz') { chars[i] = letter; if (await walk(i + 1)) return true; } chars[i] = '*'; return false; }; return walk(0); }
  async finish() { await Promise.all(this.data.players.map(async p => { const word = String(p.word || '').toLowerCase(); const valid = word.length >= 3 ? (word.includes('*') ? await this.dictionaryPattern(word) : await this.dictionaryWord(word)) : false; p.validation = valid === null ? 'unverified' : valid ? 'valid' : 'invalid'; if (valid) { let multiplier = 1; p.score = (p.wordTiles || []).reduce((n, t) => { const letter = VALUE[String(t.letter).toLowerCase()] || 0; if (t.bonus === 'double-word') multiplier *= 2; if (t.bonus === 'triple-word') multiplier *= 3; if (t.bonus === 'double-letter') return n + letter * 2; if (t.bonus === 'triple-letter') return n + letter * 3; return n + letter; }, 0) * multiplier; } else p.score = 0; p.totalScore = (p.totalScore || 0) + p.score; })); }
  beginRound() { this.data.phase = 'running'; this.data.endAt = Date.now() + ROUND; this.data.message = ''; this.event('phase_changed', { phase: 'running' }); this.event('timer_started', { phase: 'running', endAt: this.data.endAt }); this.broadcastSnapshot(); this.state.storage.setAlarm(this.nextAlarm()).catch(() => {}); }
  start() { if (!['lobby', 'results'].includes(this.data.phase)) return; this.data.phase = 'countdown'; this.data.endAt = Date.now() + 3000; this.data.finalCloseAt = 0; this.data.pool = pool(Math.max(18, 30 - (this.data.round - 1) * 3)); this.data.players.forEach(p => { p.word = ''; p.wordTiles = []; p.score = 0; }); this.data.message = 'Get ready'; this.event('phase_changed', { phase: 'countdown' }); this.event('timer_started', { phase: 'countdown', endAt: this.data.endAt }); this.broadcastSnapshot(); this.state.storage.setAlarm(this.nextAlarm()).catch(() => {}); }
  async action(clientId, role, raw) { let message; try { message = JSON.parse(raw); } catch { return this.error(this.clients.get(clientId), 'MALFORMED_MESSAGE', 'Message must be valid JSON'); } const requestId = message?.requestId; if (message?.v === 1 && message.type === 'action') message = message.payload || {}; if (!message?.type) return this.error(this.clients.get(clientId), 'INVALID_ACTION', 'Action type is required', requestId); await this.expireIfNeeded(); await this.activity(); const owner = role === 'host' || role === 'tv' || (role === 'play' && (clientId === this.data.ownerId || this.data.players.length === 1));
    if (role === 'play' && message.type === 'leave') { const socket = this.clients.get(clientId); this.data.players = this.data.players.filter(p => p.id !== clientId); if (this.data.ownerId === clientId) this.data.ownerId = this.data.players[0]?.id || null; this.event('player_left', { playerId: clientId }); try { socket?.send(JSON.stringify({ v: 1, type: 'left', seq: this.data.seq, phase: this.data.phase, payload: {} })); socket?.close(1000, 'Player left'); } catch {} this.clients.delete(clientId); if (!this.data.players.length) return this.closeRoom(); return this.broadcastSnapshot(); }
    if (message.type === 'sync') { this.broadcastSnapshot(); return this.reply(this.clients.get(clientId), 'ack', { action: 'sync' }, requestId); } if (role === 'play' && ['pointer', 'pointerEnd'].includes(message.type)) { if (message.type === 'pointer') this.data.gestures[clientId] = { playerId: clientId, tokenId: message.tokenId || null, active: true, at: Date.now() }; else delete this.data.gestures[clientId]; this.broadcastSnapshot(); return this.reply(this.clients.get(clientId), 'ack', { action: message.type }, requestId); }
    if (owner && message.type === 'start' && this.data.phase === 'lobby' && this.data.players.length) { this.start(); return this.reply(this.clients.get(clientId), 'ack', { action: 'start' }, requestId); } if (owner && message.type === 'next' && this.data.phase === 'results' && this.data.round < this.data.totalRounds) { this.data.round++; this.start(); return this.reply(this.clients.get(clientId), 'ack', { action: 'next' }, requestId); }
    if (owner && message.type === 'restart' && this.data.phase === 'final') { this.data.round = 1; this.data.phase = 'lobby'; this.data.totalRounds = this.data.mode === 'competition' ? 5 : 1; this.data.players.forEach(p => { p.word = ''; p.wordTiles = []; p.score = 0; p.totalScore = 0; delete p.validation; }); this.data.message = 'Waiting for players'; this.event('phase_changed', { phase: 'lobby' }); this.broadcastSnapshot(); return this.reply(this.clients.get(clientId), 'ack', { action: 'restart' }, requestId); }
    if (role !== 'play' || this.data.phase !== 'running') return this.error(this.clients.get(clientId), 'ACTION_NOT_ALLOWED', 'Action is not allowed in the current phase', requestId); const player = this.data.players.find(p => p.id === clientId), tile = this.data.pool.find(t => t.id === message.tokenId); if (!player) return this.error(this.clients.get(clientId), 'PLAYER_NOT_FOUND', 'Player is not connected', requestId);
    if (message.type === 'reserve' && tile && !tile.reservedBy) { tile.reservedBy = clientId; tile.reservedAt = Date.now(); this.broadcastSnapshot(); return this.reply(this.clients.get(clientId), 'ack', { action: 'reserve' }, requestId); } if (message.type === 'cancel' && tile?.reservedBy === clientId) { delete tile.reservedBy; delete tile.reservedAt; this.broadcastSnapshot(); return this.reply(this.clients.get(clientId), 'ack', { action: 'cancel' }, requestId); }
    if (message.type === 'commit' && tile?.reservedBy === clientId) { const letter = tile.letter === '*' ? String(message.letter || '').toUpperCase() : tile.letter; if (tile.letter === '*' && !/^[A-Z]$/.test(letter)) return this.error(this.clients.get(clientId), 'INVALID_WILD_LETTER', 'Wild letters require one A-Z character', requestId); player.word += letter; player.wordTiles.push({ id: tile.id, letter, bonus: tile.bonus || null, wild: tile.letter === '*' }); this.data.pool = this.data.pool.filter(t => t.id !== tile.id); this.broadcastSnapshot(); return this.reply(this.clients.get(clientId), 'ack', { action: 'commit' }, requestId); }
    if (message.type === 'releaseWord') { for (const t of player.wordTiles || []) this.data.pool.push({ id: id(), letter: t.wild ? '*' : t.letter, bonus: t.bonus || null }); player.word = ''; player.wordTiles = []; this.broadcastSnapshot(); return this.reply(this.clients.get(clientId), 'ack', { action: 'releaseWord' }, requestId); }
    return this.error(this.clients.get(clientId), 'UNKNOWN_ACTION', 'Unknown action', requestId);
  }
}
